In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.3.1+cu121


In [3]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [5]:
scalar.ndim
# scalar.shape

torch.Size([])

In [10]:
vector = torch.tensor([12, 12])

In [11]:
vector

tensor([12, 12])

In [19]:
matrix = torch.tensor([[[12, 12], [24, 24], [36, 36]], [[11, 11], [22, 22], [33, 33]]])

print(matrix.ndim)
print(matrix.shape)


3
torch.Size([2, 3, 2])


In [22]:
## Create a random tensor of shape 2, 3
random_tensor = torch.rand(3, 3, 4)

print(random_tensor)

tensor([[[0.1051, 0.0087, 0.7858, 0.6308],
         [0.4019, 0.0969, 0.7186, 0.5137],
         [0.3487, 0.8105, 0.4807, 0.2771]],

        [[0.5964, 0.5032, 0.4071, 0.0207],
         [0.9868, 0.0746, 0.7032, 0.2057],
         [0.4621, 0.8119, 0.6380, 0.7794]],

        [[0.7961, 0.1242, 0.0385, 0.9782],
         [0.2657, 0.0592, 0.7694, 0.3006],
         [0.7948, 0.4880, 0.0456, 0.8529]]])


In [23]:
## Create a random image tensor
image_tensor = torch.rand(size=(224, 244, 3))
print(image_tensor.shape, image_tensor.ndim)
print(image_tensor)

torch.Size([224, 244, 3]) 3
tensor([[[0.2063, 0.3403, 0.3635],
         [0.9222, 0.4341, 0.9913],
         [0.9736, 0.1622, 0.9846],
         ...,
         [0.4362, 0.5926, 0.6084],
         [0.0177, 0.0356, 0.7856],
         [0.9858, 0.1135, 0.4743]],

        [[0.3567, 0.8263, 0.7682],
         [0.1284, 0.8582, 0.9921],
         [0.8207, 0.9448, 0.6044],
         ...,
         [0.7692, 0.2084, 0.7781],
         [0.5375, 0.9596, 0.0645],
         [0.1319, 0.2403, 0.3646]],

        [[0.7101, 0.4097, 0.8942],
         [0.1127, 0.7162, 0.8745],
         [0.6486, 0.9723, 0.9964],
         ...,
         [0.5188, 0.5122, 0.5689],
         [0.4293, 0.5327, 0.8224],
         [0.8949, 0.3063, 0.6819]],

        ...,

        [[0.6949, 0.0302, 0.7713],
         [0.2145, 0.7107, 0.7564],
         [0.5564, 0.6629, 0.5588],
         ...,
         [0.1157, 0.4824, 0.5105],
         [0.1164, 0.4013, 0.3873],
         [0.4520, 0.8379, 0.5891]],

        [[0.4936, 0.0513, 0.6524],
         [0.1157, 0

In [28]:
torch.arange(20)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [35]:
tensor_16 = torch.rand(size=[2, 3], dtype=torch.float16)
tensor_32 = torch.rand(size=[2, 3])

print(tensor_16 * tensor_32)
print(tensor_16.dtype)
print(tensor_32.dtype)

tensor([[0.1080, 0.0476, 0.4296],
        [0.1435, 0.0399, 0.8038]])
torch.float16
torch.float32


In [43]:
first_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
sec_tensor = torch.tensor([[4, 5, 6], [1, 2, 3], [4, 5, 8]])

# first_tensor * sec_tensor


In [44]:
first_tensor + 20
sec_tensor * 100

tensor([[400, 500, 600],
        [100, 200, 300],
        [400, 500, 800]])

In [46]:
%%time
torch.matmul(first_tensor, sec_tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[18, 24, 36],
        [45, 60, 87]])

In [47]:
%%time
value = 0
for i in range(len(first_tensor)):
    value += first_tensor[i] * first_tensor[i]

CPU times: total: 0 ns
Wall time: 0 ns


In [58]:
reshape_tensor = torch.arange(1, 21)
reshape_tensor.reshape(20, 1)
reshape_tensor.reshape(20, 1).T

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]])

In [63]:
tensor_16 * tensor_16

tensor([[0.2964, 0.8037, 0.2485],
        [0.1045, 0.0919, 0.9971]], dtype=torch.float16)

In [69]:
tensor_16 @ tensor_16.T
tensor_16.reshape(2, 3)
tensor_16

tensor([[0.5444, 0.8965, 0.4985],
        [0.3232, 0.3032, 0.9985]], dtype=torch.float16)

In [71]:
tensor_16.view(3, 2)
tensor_16

tensor([[0.5444, 0.8965, 0.4985],
        [0.3232, 0.3032, 0.9985]], dtype=torch.float16)

In [ ]:
## Exercise

In [8]:
# Create a random tensor with shape (7, 7).
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
random_tensor = torch.rand([7, 7], device=device)
print(random_tensor.shape)
print(random_tensor.device)

torch.Size([7, 7])
cuda:0


In [13]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
print(device)
random_tensor_A = torch.rand([7, 7], device=device)
random_tensor_B = torch.rand([1, 7], device=device)
print(random_tensor_A.device, random_tensor_B.device)
result_tensor = random_tensor @ random_tensor_B.T

print(result_tensor)

cuda
cuda:0 cuda:0
tensor([[2.0254],
        [1.0590],
        [1.1065],
        [1.7037],
        [1.8517],
        [1.0966],
        [1.7260]], device='cuda:0')


In [22]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 42
print(f'Random Number state before setting random seed for Random Tensor A: {torch.get_rng_state()}')
torch.manual_seed(RANDOM_SEED)
print(f'Random Number Generator State before creating Tensor A: {torch.get_rng_state()}')
random_tensor_A = torch.rand([7, 7], device=device)
print(f'Random Generator State after creating Random Tensor A: {torch.get_rng_state()}')
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand([1, 7], device=device).T
print(f'Random Number Generator State after creating Random Tensor B: {torch.get_rng_state()}')
result_tensor = random_tensor_A @ random_tensor_B
print(result_tensor)
print(f'Random Tensor A: {random_tensor_A}')
print(f'Random Tensor B: {random_tensor_B}')
print(f'Are Tensor A & Tensor B equal? {random_tensor_A == random_tensor_B}')

Random Number state before setting random seed for Random Tensor A: tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
Random Number Generator State before creating Tensor A: tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
Random Generator State after creating Random Tensor A: tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
Random Number Generator State after creating Random Tensor B: tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
tensor([[1.3354],
        [0.9478],
        [0.7438],
        [1.0571],
        [0.9649],
        [1.2822],
        [1.4935]], device='cuda:0')
Random Tensor A: tensor([[0.6130, 0.0101, 0.3984, 0.0403, 0.1563, 0.4825, 0.7362],
        [0.4060, 0.5189, 0.2867, 0.2416, 0.9228, 0.8299, 0.0342],
        [0.3879, 0.0824, 0.7742, 0.2792, 0.5138, 0.2068, 0.0074],
        [0.8750, 0.9682, 0.1201, 0.1972, 0.4503, 0.0511, 0.4892],
        [0.9331, 0.3807, 0.0509, 0.2663, 0.6495, 0.2675, 0.1733],
        [0.8565, 0.2761, 0.2093, 0.0

In [27]:
import torch
RANDOM_SEED = 77

torch.manual_seed(RANDOM_SEED)
print(torch.rand([3, 2], device=device))

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
print(torch.rand([3, 2], device=device))




tensor([[0.2062, 0.6914],
        [0.7792, 0.0412],
        [0.5324, 0.3734]], device='cuda:0')
tensor([[0.6130, 0.0101],
        [0.3984, 0.0403],
        [0.1563, 0.4825]], device='cuda:0')


In [30]:
print(f'Maximum value in Tensor A is: {random_tensor_A.max()}')
print(f'Maximum value in Tensor B is: {random_tensor_B.max(), torch.max(random_tensor_B)}')

print(f'Minimum value in the Random Tensor is: {random_tensor_A.min()}')
print(f'Minimum value in the Random Tensor B is: {random_tensor_B.min()}')

Maximum value in Tensor A is: 0.9851880669593811
Maximum value in Tensor B is: (tensor(0.7362, device='cuda:0'), tensor(0.7362, device='cuda:0'))
Minimum value in the Random Tensor is: 0.007366951555013657
Minimum value in the Random Tensor B is: 0.010058844462037086


In [38]:
new_random_tensor = torch.rand([1, 1, 1, 10], device=device)

print(f'Shape of the new Random Tensor before squeezing a dimension is: {new_random_tensor.shape}')

new_random_tensor = new_random_tensor.squeeze()

print(f'Shape of the new Random Tensor after squeezing the tensor is: {new_random_tensor.shape}')

Shape of the new Random Tensor before squeezing a dimension is: torch.Size([1, 1, 1, 10])
Shape of the new Random Tensor after squeezing the tensor is: torch.Size([10])


In [41]:
import torch

output = torch.tensor([4.9988, -5.7437], device='cuda')
print(output.argmax())

print(output)

tensor(0, device='cuda:0')
tensor([ 4.9988, -5.7437], device='cuda:0')


In [44]:
image_tensor = torch.rand([3, 224, 224])
image_tensor.shape

torch.Size([3, 224, 224])